version: '3'
services:
  movie_dev_1:
    image: tomcat
    restart: always
    networks:
       - legacy
    expose:
       - "8080"
    hostname: "movie_dev_1"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie.war
  
 movie_dev_2:
    image: tomcat
    restart: always
    networks:
       - legacy
    expose:
       - "8080"
    hostname: "movie_dev_2"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie.war
       
 movie_dev_3:
    image: tomcat
    restart: always
    networks:
       - legacy
    expose:
       - "8080"
    hostname: "movie_dev_3"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie.war
       
networks:
    legacy:
      external: true
