version: '3'
services:
  movie_dev_1:
    image: tomcat_custom
    restart: always
    networks:
       - legacy
    ports:
       - "8081:8080"
    hostname: "movie_dev_1"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie.war    
networks:
    legacy:
      external: true
