version: '3'
services:
  movie_dev_1:
    image: openjdk
    restart: always
    networks:
       - legacy
    expose:
       - "8080"
    hostname: "movie_dev_1"
    volumes:
       - ./movie.jar:/movie.jar
    command: java -jar movie.jar
  
  movie_dev_2:
    image: openjdk
    restart: always
    networks:
       - legacy
    expose:
       - "8080"
    hostname: "movie_dev_2"
    volumes:
       - ./movie.jar:/movie.jar
    command: java -jar movie.jar
       
  movie_dev_3:
    image: openjdk
    restart: always
    networks:
       - legacy
    expose:
       - "8080"
    hostname: "movie_dev_3"
    volumes:
       - ./movie.jar:/movie.jar
    command: java -jar movie.jar
networks:
    legacy:
      external: true
