version: '3'
services:
  movie_dev:
    image: tomcat
    networks:
       - legacy
    hostname: "movie_dev_1"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie_dev.war
networks:
    legacy:
      external: true
