version: '3'
services:
   movie_dev_1:
    image: java
    restart: always
    networks:
       - legacy
    expose:
       - "8080"
    hostname: "movie_dev_1"
    volumes:
       - ./movie.war:movie.war
       
networks:
    legacy:
      external: true
