version: '3'
services:
  movie_dev_1:
    image: tomcat
    restart: always
    networks:
       - legacy
    hostname: "movie_dev_1"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie_dev.war
  
  movie_dev_2:
    image: tomcat
    restart: always
    networks:
       - legacy
    hostname: "movie_dev_2"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie_dev.war
       
  movie_dev_3:
    image: tomcat
    restart: always
    networks:
       - legacy
    hostname: "movie_dev_3"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie_dev.war
networks:
    legacy:
      external: true
