version: '3'
services:
  movie_dev_1:
    image: tomcat:8-jre8-slim
    restart: always
    networks:
       - legacy
    ports:
       - "8081:8080"
    hostname: "movie_dev_1"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie.war
    command: sed -i.bak -e "s/securerandom.source=file:\/dev\/random/securerandom.source=file:\/dev\/urandom/g" -e "s/securerandom.strongAlgorithms=NativePRNGBlocking/securerandom.strongAlgorithms=NativePRNG/g" $JAVA_HOME/lib/security/java.security
      
    
networks:
    legacy:
      external: true
