version: '3'
services:
  movie_dev_1:
    image: tomcat
    restart: always
    networks:
       - legacy
    hostname: "movie_dev_1"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie.war
    
networks:
    legacy:
      external: true
