version: '3'
services:
  movie:
    image: tomcat
    ports:
      - "80:8080"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie.war
       - ./movie:/usr/local/tomcat/webapps/movie
       
    command: "rm -Rf /usr/local/tomcat/webapps/ROOT; mv /usr/local/tomcat/webapps/movie /usr/local/tomcat/webapps/ROOT"
