version: '3'

services:
   nginx_server:
      image: nginx
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
      networks:
         - legacy
      hostname: "nginx"
 
      ports:
         - "80:80"
networks:
    legacy:
      external: true

   

