version: '3'
services:
  movie_deploy_1:
    image: tomcat
    restart: always
    networks:
       - legacy
    hostname: "movie_deploy_1"
    volumes:
       - ./movie:/usr/local/tomcat/webapps/movie
   
networks:
    legacy:
      external: true
