version: '3'
services:
  movie_deploy:
    image: tomcat
    networks:
       - legacy
    hostname: "movie_deploy_1"
    volumes:
       - ./movie.war:/usr/local/tomcat/webapps/movie.war
networks:
    legacy:
      external: true
